#configure workflow when code is pushed to the master branch
name: Azure Pipeline
on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Run Python script
        run: |
          python src/azuremlapp/utils/fraud_train.py

      - name: Check Pickle File Exists(Model file)
        run: |
          if [ -f "outputs/fraud_detection_model.pkl" ]; then
            echo "Model file exists."
          else
            echo "Model file does not exist."
            exit 1
          fi
      - name: Test Score
        run: |
          python src/azuremlapp/utils/score.py
     